# Remmina - The GTK+ Remote Desktop Client
# Copyright (C) 2014-2017 Antenore Gatta, Giovanni Panozzo
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
#   In addition, as a special exception, the copyright holders give
#   permission to link the code of portions of this program with the
#   OpenSSL library under certain conditions as described in each
#   individual source file, and distribute linked combinations
#   including the two.
#   You must obey the GNU General Public License in all respects
#   for all of the code used other than OpenSSL.#   If you modify
#   file(s) with this exception, you may extend this exception to your
#   version of the file(s), but you are not obligated to do so.#   If you
#   do not wish to do so, delete this exception statement from your
#   version.#   If you delete this exception statement from all source
#   files in the program, then also delete it here.
#
#

sudo: required
language: generic

group: edge

services:
- docker

env:
  global:
  - BUILD_FOLDER=build
  - DEB_PPA='ppa:remmina-ppa-team/remmina-next'
  - DEB_EXTRA_DEPS='libspice-protocol-dev libspice-client-gtk-3.0-dev'
  - DEB_BUILD_OPTIONS='-DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_APPINDICATOR=OFF'
  - DOCKER_IMAGE=ubuntu:xenial
  - SNAP_PRIME_ON_PULL_REQUEST=true
  - SNAP_TRANSFER_SH_UPLOAD_ON_PULL_REQUEST=true
  - SNAP_UNSTABLE_CHANNEL=edge
  - SNAP_RELEASE_CHANNEL=stable
  - SNAPCRAFT_CONFIG_KEY=$encrypted_8816994192a9_key
  - SNAPCRAFT_CONFIG_IV=$encrypted_8816994192a9_iv
  matrix:
  - BUILD_TYPE=deb
  - BUILD_TYPE=snap
  - BUILD_TYPE=snap ARCH=i386


before_install:
  - scripts/travis-build.sh before_install

install:
  - scripts/travis-build.sh install

script:
  - scripts/travis-build.sh script

after_success:
  - scripts/travis-build.sh after_success

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/travis-build.sh deploy-unstable
    on:
      condition: $BUILD_TYPE = snap
      branch: next

  - provider: script
    skip_cleanup: true
    script: scripts/travis-build.sh deploy-release
    on:
      condition: $BUILD_TYPE = snap
      branch: next
      tags: true

notifications:
  email:
    - antenore@simbiosi.org
    - giovanni@panozzo.it
  irc:
      channels:
          - "chat.freenode.net#remmina"
      template:
          - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
          - "Change view : %{compare_url}"
          - "Build details : %{build_url}"
# EOF #
